title = "Fleming Systems LLC"
baseURL = "https://fleming.systems"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[menu]
    [[menu.main]]
    name = "Contact"
    url = "/contactme/"

    [[menu.main]]
    name = "About Me"
    url = "/aboutme/"

[params]
  favicon = "/images/MediumFSIcon.png"
  site_logo = "/images/MediumBanner.png"
  description = "Fleming Systems LLC -- IT Consulting Needs"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://linkedin.com/in/trfleming3745"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "images/mainbackground.jpg"
  recent_posts_number = 2
